services:
  storefront_beauty:
    build:
      context: .
      args:
        NEXT_PUBLIC_MEDUSA_BACKEND_URL: ${NEXT_PUBLIC_MEDUSA_BACKEND_URL}
        NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY: ${NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY}
        NEXT_PUBLIC_STORE_CATEGORY_CHANNEL: ${NEXT_PUBLIC_STORE_CATEGORY_CHANNEL:-sminka}
        NEXT_PUBLIC_DEFAULT_REGION: ${NEXT_PUBLIC_DEFAULT_REGION:-dk}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    container_name: medusa_storefront_beauty
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - HOSTNAME=0.0.0.0
      - MEDUSA_BACKEND_URL=${MEDUSA_BACKEND_URL:-http://medusa_backend:9000}
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=${NEXT_PUBLIC_MEDUSA_BACKEND_URL}
      - NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY}
      - NEXT_PUBLIC_STORE_CATEGORY_CHANNEL=${NEXT_PUBLIC_STORE_CATEGORY_CHANNEL:-sminka}
      - NEXT_PUBLIC_DEFAULT_REGION=${NEXT_PUBLIC_DEFAULT_REGION:-dk}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    env_file:
      - path: .env
        required: false
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
